<?php
/**
 * Copyright (c) 2020 PublishPress
 *
 * GNU General Public License, Free Software Foundation <https://www.gnu.org/licenses/gpl-3.0.html>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     PPProAds
 * @category    Core
 * @author      PublishPress
 * @copyright   Copyright (c) 2020 PublishPress. All rights reserved.
 **/

use Pimple\Container;
use PPProAds\ServicesProvider;

if (!defined('PP_PRO_ADS_LOADED')) {
    define('PP_PRO_ADS_VERSION', '0.1.0');
    define('PP_PRO_ADS_BASE_PATH', __DIR__);
    define('PP_PRO_ADS_SRC_PATH', PP_PRO_ADS_BASE_PATH . DIRECTORY_SEPARATOR . 'src');

    if (file_exists(__DIR__ . DIRECTORY_SEPARATOR . 'vendor/autoload.php')) {
        /*
         * We need to check this because of the tests. Since we use composer the tests already loaded the class and
         * the autoload.php file doesn't check that (it is generated by composer).
         *
         * Make sure to update the class name after running composer update or dump autoload.
         */
        if (!class_exists('ComposerAutoloaderInit106cb18fa68dde0bb4797e9eda58c780')) {
            require_once __DIR__ . DIRECTORY_SEPARATOR . 'vendor/autoload.php';
        }
    }

    add_action('pp_pro_ads_init', function () {
        $container = new Container();
        $container->register(new ServicesProvider());

        // Load the modules
        $module = $container['module_top_banner'];
        $module->init();
    });

    define('PP_PRO_ADS_LOADED', true);
}
