<?php

/********************************************************************************
 * This file was automatically generated by the version-loader-generator script
 * whenever the composer update command is run.
 *
 * WARNING: Do not modify this file directly. Your changes will be overwritten.
 *******************************************************************************/

use PublishPress\WordpressVersionNotices\Versions;

class VersionsCest
{
    public function testAllVersionsAreRegistered(WpunitTester $I)
    {
        $versions = Versions::getInstance();

        $registeredVersions = $versions->getVersions();

        $I->assertNotEmpty($registeredVersions);
        $I->assertEquals([
            '2.0.0.1' => 'PublishPress\WordpressVersionNotices\initialize2Dot0Dot0Dot1',
            '2.0.0.2' => 'PublishPress\WordpressVersionNotices\initialize2Dot0Dot0Dot2',
            '2.2.1' => 'PublishPress\WordpressVersionNotices\initialize2Dot2Dot1',
        ], $registeredVersions);
    }

    public function testLatestVersionIsTheCurrentVersion(WpunitTester $I)
    {
        $versions = Versions::getInstance();

        $latestVersion = $versions->latestVersion();

        $I->assertEquals('2.2.1', $latestVersion);
    }

    public function testLatestVersionCallbackIsTheLastOne(WpunitTester $I)
    {
        $versions = Versions::getInstance();

        $latestVersionCallback = $versions->latestVersionCallback();

        $I->assertEquals('PublishPress\WordpressVersionNotices\initialize2Dot2Dot1', $latestVersionCallback);
    }

    public function testInitializeLatestVersion(WpunitTester $I)
    {
        $versions = Versions::getInstance();

        $versions->initializeLatestVersion();

        $I->assertTrue(class_exists('PublishPress\WordpressVersionNotices\ServicesProvider'));

        $didAction = (bool)did_action('publishpress_wordpress_version_notices_2Dot2Dot1_initialized');
        $I->assertTrue($didAction);
    }
}
