name: PHP v5 Support

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

permissions:
  contents: read

jobs:
  php5_check:
    uses: publishpress/github-workfows/.github/workflows/php5-support.yml@main
